export { EmptyFollowsView } from './components/EmptyFollowsView'
export { EmptyGamesView } from './components/EmptyGamesView'
export { EmptyStudentView } from './components/EmptyStudentView'
export { StudentCard } from './components/StudentCard'
export { StudentCardList } from './components/StudentCardList'
export { StudentProfileView } from './components/StudentProfileView'
export { StudentView } from './components/StudentView'
export type { StudentCardProps } from './types/student.types'
export { Dashboard as StudentDashboard } from './pages/dashboard'
