export { EmptyFollowsView } from './components/EmptyFollowsView'
export { EmptyGamesView } from './components/EmptyGamesView'
export { EmptyStudentView } from './components/EmptyStudentView'
export { StudentCard } from './components/StudentCard'
export { StudentCardList } from './components/StudentCardList'
export { StudentView } from './components/StudentView'
export type { StudentCardProps } from './types/student.types'
export { Dashboard as StudentDashboard } from './pages/dashboard'
export { StudentFilesPage } from './pages/files'
export { StudentNotesPage } from './pages/notes'
export { StudentTasksPage } from './pages/tasks'
export { StudentSettingsPage } from './pages/settings'
export { Chat as StudentChat } from './pages/chat'
export { StudentViewPage } from './pages/view'
