export { InstitutionAdminWorkspaceShell } from './components/InstitutionAdminWorkspaceShell'
export { InstitutionDashboard as InstitutionAdminDashboardPage } from './pages/dashboard'
export { InstitutionTeachers as InstitutionAdminTeachersPage } from './pages/teacher'
export { InstitutionStudents as InstitutionAdminStudentsPage } from './pages/students'
export { InstitutionUsers as InstitutionAdminUsersPage } from './pages/users'
export { InstitutionFaculties as InstitutionAdminFacultiesPage } from './pages/faculties'
export { InstitutionClassrooms as InstitutionAdminClassroomsPage } from './pages/classrooms'
export { AdminLicenses as InstitutionAdminLicensesPage } from './pages/licenses'
export { InstitutionUsage as InstitutionAdminUsagePage } from './pages/usage'
export { InstitutionGDPRRequest as InstitutionAdminGDPRRequestPage } from './pages/gdpr-request'
export { AdminBilling as InstitutionAdminBillingPage } from './pages/billing'
export { InstitutionCourses as InstitutionAdminCoursesPage } from './pages/courses'
export { AdminAnalytics as InstitutionAdminAnalyticsPage } from './pages/analytics'
export { InstitutionCloudStorage as InstitutionAdminCloudStoragePage } from './pages/cloud-storage'
export { InstitutionAuditLogs as InstitutionAdminAuditLogsPage } from './pages/audit-logs'
export { AdminSettings as InstitutionAdminSettingsPage } from './pages/settings'
