import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import type { DateRange } from 'react-day-picker'
import { useTranslation } from 'react-i18next'
import { format } from 'date-fns'
import { toast } from 'sonner'

import { Button } from '@/components/ui/button'
import { Text } from '@/components/ui/text'
import { StepperProgressBarTitles } from '@/components/shared'
import { useUser } from '@/contexts/user'
import type { ProgrammeProgressionType } from '../types/programme.types'
import type { ProgrammeOfferingStatus } from '../types/programme-offering.types'
import { InstitutionAdminWorkspaceShell } from '../components/InstitutionAdminWorkspaceShell'
import { WizardBreadcrumb } from '../components/WizardBreadcrumb'
import { FacultyStep } from '../components/FacultyStep'
import { ProgrammeStep } from '../components/ProgrammeStep'
import { ProgrammeOfferingStep } from '../components/ProgrammeOfferingStep'
import { CohortStep } from '../components/CohortStep'
import { CohortOfferingStep } from '../components/CohortOfferingStep'
import { ClassGroupStep } from '../components/ClassGroupStep'
import { ClassGroupOfferingStep } from '../components/ClassGroupOfferingStep'
import { FacultyStructureSummaryStep } from '../components/FacultyStructureSummaryStep'
import {
  appendProgrammeStructureToExistingFaculty,
  createFacultyStructure,
} from '../api/facultyStructureApi'
import { listFacultiesByInstitution } from '../api/facultiesApi'
import {
  buildCohortNameFromTermCode,
  buildTermCode,
  isAutoGeneratedCohortName,
  isAutoGeneratedTermCode,
  suggestTermCode,
} from '../utils/termCode'

type BaseOfferingDraft = {
  id: string
  status: ProgrammeOfferingStatus
  dateRange: DateRange | undefined
}

function createBaseOffering(): BaseOfferingDraft {
  return { id: crypto.randomUUID(), status: 'draft', dateRange: undefined }
}

const WIZARD_STEP_COUNT = 8

type OfferingDraft = {
  id: string
  academicYear: number
  termCode: string
  status: ProgrammeOfferingStatus
  dateRange: DateRange | undefined
}

function createEmptyOffering(): OfferingDraft {
  const currentYear = new Date().getFullYear()
  return {
    id: crypto.randomUUID(),
    academicYear: currentYear,
    termCode: suggestTermCode(currentYear),
    status: 'draft',
    dateRange: undefined,
  }
}

export function InstitutionFacultiesCreate() {
  const { t, i18n } = useTranslation('features.institution-admin')
  const { getUserInstitutionId } = useUser()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [wizardStep, setWizardStep] = useState(1)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [existingFacultyId, setExistingFacultyId] = useState<string | null>(null)

  const [facultyName, setFacultyName] = useState('')
  const [facultyDescription, setFacultyDescription] = useState('')

  const [programmeName, setProgrammeName] = useState('')
  const [programmeDescription, setProgrammeDescription] = useState('')
  const [durationYears, setDurationYears] = useState<number>(3)
  const [progressionType, setProgressionType] = useState<ProgrammeProgressionType>('year_group')

  const [offerings, setOfferings] = useState<OfferingDraft[]>(() => [createEmptyOffering()])

  const [cohortName, setCohortName] = useState('')
  const [cohortAcademicYear, setCohortAcademicYear] = useState<number>(new Date().getFullYear())
  const [cohortOfferings, setCohortOfferings] = useState<BaseOfferingDraft[]>(() => [
    createBaseOffering(),
  ])

  const [classGroupName, setClassGroupName] = useState('')
  const [classGroupDescription, setClassGroupDescription] = useState('')
  const [classGroupOfferings, setClassGroupOfferings] = useState<BaseOfferingDraft[]>(() => [
    createBaseOffering(),
  ])

  // Refs track whether the user has manually overridden an auto-derived field.
  // This lets us re-derive when the source changes without trampling intentional edits.
  const termCodeAutoRef = useRef(true)
  const cohortNameAutoRef = useRef(true)

  // Stable first offering term code so the cohort-name effect has a precise dependency.
  const firstOfferingTermCode = offerings[0]?.termCode ?? ''
  const lang = i18n.language.startsWith('de') ? 'de' : 'en'

  // Auto-derive term code from programme name (e.g. "Gestalter für Visuelles Marketing" → "GVM-2026").
  // Only applies while the term code has not been manually edited OR still matches the auto pattern.
  useEffect(() => {
    if (!programmeName.trim()) return
    if (!termCodeAutoRef.current) return
    const year = new Date().getFullYear()
    const suggested = buildTermCode(programmeName, year)
    setOfferings((rows) =>
      rows.map((row) =>
        isAutoGeneratedTermCode(row.termCode) || row.termCode === ''
          ? { ...row, termCode: suggested }
          : row,
      ),
    )
  }, [programmeName])

  // Auto-derive cohort name from the first offering's term code (e.g. "GVM-2026" → "GVM Jahrgang 2026").
  // Only applies while the cohort name has not been manually edited OR still matches the auto pattern.
  useEffect(() => {
    if (!firstOfferingTermCode) return
    if (!cohortNameAutoRef.current) return
    if (!isAutoGeneratedTermCode(firstOfferingTermCode)) return
    const suggested = buildCohortNameFromTermCode(firstOfferingTermCode, lang)
    setCohortName((current) =>
      isAutoGeneratedCohortName(current) || current === '' ? suggested : current,
    )
  }, [firstOfferingTermCode, lang])

  const progressionOptions = useMemo(
    (): readonly ProgrammeProgressionType[] => ['year_group', 'stage'],
    [],
  )

  const wizardSteps = useMemo(
    () =>
      [
        { title: t('faculties.wizard.steps.faculty') },
        { title: t('faculties.wizard.steps.programme') },
        { title: t('faculties.wizard.steps.programmeOffering') },
        { title: t('faculties.wizard.steps.cohort') },
        { title: t('faculties.wizard.steps.cohortOffering') },
        { title: t('faculties.wizard.steps.classGroup') },
        { title: t('faculties.wizard.steps.classGroupOffering') },
        { title: t('faculties.wizard.steps.summary') },
      ] as const,
    [t],
  )

  useEffect(() => {
    const facultyIdParam = searchParams.get('facultyId')
    const institutionId = getUserInstitutionId()
    if (!facultyIdParam || !institutionId) {
      return
    }

    let cancelled = false

    void (async () => {
      try {
        const faculties = await listFacultiesByInstitution(institutionId)
        const match = faculties.find((f) => f.id === facultyIdParam)
        if (cancelled) {
          return
        }
        if (!match) {
          toast.error(t('faculties.wizard.prefill.facultyNotFound'))
          navigate('/institution_admin/faculties')
          return
        }
        setExistingFacultyId(match.id)
        setFacultyName(match.name ?? '')
        setFacultyDescription(match.description ?? '')
        setWizardStep(2)
      } catch {
        if (!cancelled) {
          toast.error(t('faculties.wizard.prefill.loadFailed'))
        }
      }
    })()

    return () => {
      cancelled = true
    }
  }, [searchParams, getUserInstitutionId, navigate, t])

  const handleBackToFaculties = () => {
    navigate('/institution_admin/faculties')
  }

  function handleWizardPrevious() {
    if (existingFacultyId && wizardStep === 2) {
      navigate(`/institution_admin/faculties/${existingFacultyId}/programmes`)
      return
    }
    setWizardStep((prev) => Math.max(1, prev - 1))
  }

  function handleWizardNext() {
    setWizardStep((prev) => Math.min(WIZARD_STEP_COUNT, prev + 1))
  }

  function formatDateRangeLabel(dateRange: DateRange | undefined): string {
    const from = dateRange?.from ? format(dateRange.from, 'MMM d, yyyy') : '—'
    const to = dateRange?.to ? format(dateRange.to, 'MMM d, yyyy') : '—'
    return `${from} - ${to}`
  }

  function formatStatusLabel(status: ProgrammeOfferingStatus): string {
    if (status === 'active') return t('faculties.wizard.offering.statusActive')
    if (status === 'draft') return t('faculties.wizard.offering.statusDraft')
    return t('faculties.wizard.offering.statusArchived')
  }

  const programmeOfferingBreadcrumb = useMemo(() => {
    const first = offerings[0]
    if (!first) return ''
    const code = first.termCode?.trim() || String(first.academicYear)
    return `${code} · ${formatDateRangeLabel(first.dateRange)}`
  }, [offerings])

  const cohortOfferingBreadcrumb = useMemo(() => {
    const first = cohortOfferings[0]
    if (!first) return ''
    return formatDateRangeLabel(first.dateRange)
  }, [cohortOfferings])

  const classGroupOfferingBreadcrumb = useMemo(() => {
    const first = classGroupOfferings[0]
    if (!first) return ''
    return formatDateRangeLabel(first.dateRange)
  }, [classGroupOfferings])

  async function handleFinish() {
    const institutionId = getUserInstitutionId()

    if (!institutionId) {
      toast.error(t('faculties.wizard.submit.missingInstitution'))
      return
    }

    const sharedPayload = {
      programme: {
        name: programmeName,
        description: programmeDescription.trim() || null,
        durationYears,
        progressionType,
      },
      programmeOfferings: offerings.map((offering) => ({
        academicYear: offering.academicYear,
        termCode: offering.termCode.trim() || null,
        status: offering.status,
        dateRange: offering.dateRange,
      })),
      cohort: {
        name: cohortName,
        description: null,
        academicYear: cohortAcademicYear,
      },
      cohortOfferings: cohortOfferings.map((offering) => ({
        status: offering.status,
        dateRange: offering.dateRange,
      })),
      classGroup: {
        name: classGroupName,
        description: classGroupDescription.trim() || null,
      },
      classGroupOfferings: classGroupOfferings.map((offering) => ({
        status: offering.status,
        dateRange: offering.dateRange,
      })),
    }

    setIsSubmitting(true)
    try {
      if (existingFacultyId) {
        await appendProgrammeStructureToExistingFaculty({
          institutionId,
          facultyId: existingFacultyId,
          ...sharedPayload,
        })
        toast.success(t('faculties.wizard.submit.successAppendTitle'), {
          description: t('faculties.wizard.submit.successAppendDescription', {
            facultyName: facultyName.trim() || t('faculties.card.untitled'),
          }),
        })
        navigate(`/institution_admin/faculties/${existingFacultyId}/programmes`)
      } else {
        await createFacultyStructure({
          institutionId,
          faculty: {
            name: facultyName,
            description: facultyDescription.trim() || null,
          },
          ...sharedPayload,
        })
        toast.success(t('faculties.wizard.submit.successTitle'), {
          description: t('faculties.wizard.submit.successDescription', {
            facultyName: facultyName.trim() || t('faculties.card.untitled'),
          }),
        })
        navigate('/institution_admin/faculties')
      }
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : t('faculties.wizard.submit.errorFallback'),
      )
    } finally {
      setIsSubmitting(false)
    }
  }

  function updateOffering(id: string, patch: Partial<OfferingDraft>) {
    // A manual termCode edit disables auto-derivation for all future name changes.
    if (patch.termCode !== undefined) {
      termCodeAutoRef.current = false
    }

    setOfferings((rows) =>
      rows.map((row) => {
        if (row.id !== id) return row
        const next = { ...row, ...patch }
        // When only the academic year changes, re-derive the term code using the
        // programme name (consistent with the new INITIALS-YEAR format) unless
        // the user has manually overridden it.
        if (patch.academicYear != null && patch.termCode === undefined && termCodeAutoRef.current) {
          next.termCode = programmeName.trim()
            ? buildTermCode(programmeName, patch.academicYear)
            : suggestTermCode(patch.academicYear)
        }
        return next
      }),
    )
  }

  function addOffering() {
    setOfferings((rows) => [...rows, createEmptyOffering()])
  }

  function removeOffering(id: string) {
    setOfferings((rows) => (rows.length <= 1 ? rows : rows.filter((r) => r.id !== id)))
  }

  function updateCohortOffering(id: string, patch: Partial<BaseOfferingDraft>) {
    setCohortOfferings((rows) => rows.map((r) => (r.id === id ? { ...r, ...patch } : r)))
  }

  function addCohortOffering() {
    setCohortOfferings((rows) => [...rows, createBaseOffering()])
  }

  function removeCohortOffering(id: string) {
    setCohortOfferings((rows) => (rows.length <= 1 ? rows : rows.filter((r) => r.id !== id)))
  }

  function updateClassGroupOffering(id: string, patch: Partial<BaseOfferingDraft>) {
    setClassGroupOfferings((rows) => rows.map((r) => (r.id === id ? { ...r, ...patch } : r)))
  }

  function addClassGroupOffering() {
    setClassGroupOfferings((rows) => [...rows, createBaseOffering()])
  }

  function removeClassGroupOffering(id: string) {
    setClassGroupOfferings((rows) => (rows.length <= 1 ? rows : rows.filter((r) => r.id !== id)))
  }

  const breadcrumbValues = useMemo(
    () => [
      facultyName.trim(),
      programmeName.trim(),
      programmeOfferingBreadcrumb,
      cohortName.trim(),
      cohortOfferingBreadcrumb,
      classGroupName.trim(),
      classGroupOfferingBreadcrumb,
      t('faculties.wizard.steps.summary'),
    ],
    [
      facultyName,
      programmeName,
      programmeOfferingBreadcrumb,
      cohortName,
      cohortOfferingBreadcrumb,
      classGroupName,
      classGroupOfferingBreadcrumb,
      t,
    ],
  )

  const renderWizardStep = (_step: { title: string }, index: number) => {
    const priorItems = breadcrumbValues.slice(0, index).filter(Boolean)

    let stepContent: ReactNode

    switch (index) {
      case 0:
        stepContent = (
          <FacultyStep
            name={facultyName}
            onNameChange={setFacultyName}
            description={facultyDescription}
            onDescriptionChange={setFacultyDescription}
            readOnly={Boolean(existingFacultyId)}
          />
        )
        break

      case 1:
        stepContent = (
          <ProgrammeStep
            name={programmeName}
            onNameChange={setProgrammeName}
            description={programmeDescription}
            onDescriptionChange={setProgrammeDescription}
            durationYears={durationYears}
            onDurationChange={setDurationYears}
            progressionType={progressionType}
            onProgressionTypeChange={setProgressionType}
            progressionOptions={progressionOptions}
          />
        )
        break

      case 2:
        stepContent = (
          <ProgrammeOfferingStep
            offerings={offerings}
            onUpdateOffering={updateOffering}
            onAddOffering={addOffering}
            onRemoveOffering={removeOffering}
            programmeName={programmeName}
            durationYears={durationYears}
          />
        )
        break

      case 3:
        stepContent = (
          <CohortStep
            name={cohortName}
            onNameChange={(value) => {
              cohortNameAutoRef.current = false
              setCohortName(value)
            }}
            academicYear={cohortAcademicYear}
            onAcademicYearChange={setCohortAcademicYear}
          />
        )
        break

      case 4:
        stepContent = (
          <CohortOfferingStep
            offerings={cohortOfferings}
            onUpdateOffering={updateCohortOffering}
            onAddOffering={addCohortOffering}
            onRemoveOffering={removeCohortOffering}
          />
        )
        break

      case 5:
        stepContent = (
          <ClassGroupStep
            name={classGroupName}
            onNameChange={setClassGroupName}
            description={classGroupDescription}
            onDescriptionChange={setClassGroupDescription}
            termCode={offerings[0]?.termCode}
          />
        )
        break

      case 6:
        stepContent = (
          <ClassGroupOfferingStep
            offerings={classGroupOfferings}
            onUpdateOffering={updateClassGroupOffering}
            onAddOffering={addClassGroupOffering}
            onRemoveOffering={removeClassGroupOffering}
          />
        )
        break

      case 7:
        stepContent = (
          <FacultyStructureSummaryStep
            intro={t('faculties.wizard.summary.intro')}
            rows={[
              { label: t('faculties.wizard.summary.rows.faculty'), value: facultyName || '—' },
              { label: t('faculties.wizard.summary.rows.programme'), value: programmeName || '—' },
              {
                label: t('faculties.wizard.summary.rows.programmeDuration'),
                value: t('faculties.wizard.programme.durationValue', { count: durationYears }),
              },
              {
                label: t('faculties.wizard.summary.rows.progression'),
                value: t(`faculties.wizard.programme.progression.${progressionType}`),
              },
              { label: t('faculties.wizard.summary.rows.cohort'), value: cohortName || '—' },
              {
                label: t('faculties.wizard.summary.rows.cohortAcademicYear'),
                value: String(cohortAcademicYear),
              },
              {
                label: t('faculties.wizard.summary.rows.classGroup'),
                value: classGroupName || '—',
              },
            ]}
            columns={{
              index: t('faculties.wizard.summary.columns.index'),
              label: t('faculties.wizard.summary.columns.label'),
              status: t('faculties.wizard.summary.columns.status'),
              startsAt: t('faculties.wizard.summary.columns.startsAt'),
              endsAt: t('faculties.wizard.summary.columns.endsAt'),
            }}
            sectionTitles={{
              programmeOfferings: t('faculties.wizard.summary.sections.programmeOfferings'),
              cohortOfferings: t('faculties.wizard.summary.sections.cohortOfferings'),
              classGroupOfferings: t('faculties.wizard.summary.sections.classGroupOfferings'),
            }}
            programmeOfferings={offerings.map((offering) => ({
              label: offering.termCode || String(offering.academicYear),
              status: formatStatusLabel(offering.status),
              startsAt: offering.dateRange?.from
                ? format(offering.dateRange.from, 'MMM d, yyyy')
                : '—',
              endsAt: offering.dateRange?.to ? format(offering.dateRange.to, 'MMM d, yyyy') : '—',
            }))}
            cohortOfferings={cohortOfferings.map((offering, offeringIndex) => ({
              label: t('faculties.wizard.summary.labels.offeringNumber', {
                count: offeringIndex + 1,
              }),
              status: formatStatusLabel(offering.status),
              startsAt: offering.dateRange?.from
                ? format(offering.dateRange.from, 'MMM d, yyyy')
                : '—',
              endsAt: offering.dateRange?.to ? format(offering.dateRange.to, 'MMM d, yyyy') : '—',
            }))}
            classGroupOfferings={classGroupOfferings.map((offering, offeringIndex) => ({
              label: t('faculties.wizard.summary.labels.offeringNumber', {
                count: offeringIndex + 1,
              }),
              status: formatStatusLabel(offering.status),
              startsAt: offering.dateRange?.from
                ? format(offering.dateRange.from, 'MMM d, yyyy')
                : '—',
              endsAt: offering.dateRange?.to ? format(offering.dateRange.to, 'MMM d, yyyy') : '—',
            }))}
          />
        )
        break

      default:
        return null
    }

    return (
      <div className="flex w-full flex-col gap-4">
        <WizardBreadcrumb items={priorItems} />
        {stepContent}
      </div>
    )
  }

  return (
    <InstitutionAdminWorkspaceShell>
      <div className="mx-auto flex w-full max-w-4xl flex-col gap-8 px-2 pb-12 pt-4">
        <div className="flex flex-col gap-4">
          <Button
            variant="ghost"
            type="button"
            className="w-fit gap-2 px-0"
            onClick={handleBackToFaculties}
          >
            <ArrowLeft className="size-4" />
            {t('faculties.wizard.backToList')}
          </Button>
          <div>
            <Text
              as="h1"
              variant="h1"
              className="text-2xl font-bold"
            >
              {t('faculties.create')}
            </Text>
            <Text
              as="p"
              variant="body"
              color="muted"
            >
              {t('faculties.createSubtitle')}
            </Text>
          </div>
        </div>

        <div className="flex w-full flex-col gap-6">
          <StepperProgressBarTitles
            steps={wizardSteps}
            value={wizardStep}
            defaultValue={1}
            onValueChange={setWizardStep}
            className="mx-auto max-w-4xl space-y-8"
            renderContent={renderWizardStep}
          />

          <div className="mx-auto flex w-full max-w-4xl flex-wrap justify-between gap-3 border-t border-border pt-6">
            <Button
              type="button"
              variant="outline"
              onClick={handleWizardPrevious}
              disabled={wizardStep <= 1}
            >
              {t('faculties.wizard.actions.previous')}
            </Button>

            {wizardStep < WIZARD_STEP_COUNT ? (
              <Button
                type="button"
                variant="darkblue"
                onClick={handleWizardNext}
              >
                {t('faculties.wizard.actions.next')}
              </Button>
            ) : (
              <Button
                type="button"
                variant="darkblue"
                onClick={handleFinish}
                disabled={isSubmitting}
              >
                {isSubmitting
                  ? t('faculties.wizard.actions.finishing')
                  : t('faculties.wizard.actions.finish')}
              </Button>
            )}
          </div>
        </div>
      </div>
    </InstitutionAdminWorkspaceShell>
  )
}
