import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'

import { Button } from '@/components/ui/button'
import { Text } from '@/components/ui/text'
import { StepperProgressBarTitles } from '@/components/shared'
import { useUser } from '@/contexts/user'
import type { ProgrammeProgressionType } from '../types/programme.types'
import { InstitutionAdminWorkspaceShell } from '../components/InstitutionAdminWorkspaceShell'
import { WizardBreadcrumb } from '../components/WizardBreadcrumb'
import { FacultyStep } from '../components/FacultyStep'
import { ProgrammeStep } from '../components/ProgrammeStep'
import { CohortStep } from '../components/CohortStep'
import { ClassGroupStep } from '../components/ClassGroupStep'
import { FacultyStructureSummaryStep } from '../components/FacultyStructureSummaryStep'
import {
  appendProgrammeStructureToExistingFaculty,
  createFacultyStructure,
} from '../api/facultyStructureApi'
import { listFacultiesByInstitution } from '../api/facultiesApi'
import {
  buildCohortNameFromTermCode,
  clampAcademicYear,
  deriveSuggestedTermCode,
  isAutoGeneratedCohortName,
  isAutoGeneratedTermCode,
  suggestTermCode,
} from '../utils/termCode'

const WIZARD_STEP_COUNT = 5

export function InstitutionFacultiesCreate() {
  const { t, i18n } = useTranslation('features.institution-admin')
  const { getUserInstitutionId } = useUser()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [wizardStep, setWizardStep] = useState(1)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [existingFacultyId, setExistingFacultyId] = useState<string | null>(null)

  const [facultyName, setFacultyName] = useState('')
  const [facultyDescription, setFacultyDescription] = useState('')

  const [programmeName, setProgrammeName] = useState('')
  const [programmeDescription, setProgrammeDescription] = useState('')
  const [durationYears, setDurationYears] = useState<number>(3)
  const [progressionType, setProgressionType] = useState<ProgrammeProgressionType>('year_group')

  const [cohortName, setCohortName] = useState('')
  const [cohortAcademicYear, setCohortAcademicYear] = useState<number>(() =>
    clampAcademicYear(new Date().getFullYear()),
  )

  const [classGroupName, setClassGroupName] = useState('')
  const [classGroupDescription, setClassGroupDescription] = useState('')

  const cohortNameAutoRef = useRef(true)

  const lang = i18n.language.startsWith('de') ? 'de' : 'en'
  const defaultProgrammeOfferingYear = clampAcademicYear(new Date().getFullYear())
  const defaultProgrammeOfferingTermCode = useMemo(
    () =>
      deriveSuggestedTermCode(programmeName, defaultProgrammeOfferingYear, durationYears) ||
      suggestTermCode(defaultProgrammeOfferingYear),
    [programmeName, defaultProgrammeOfferingYear, durationYears],
  )

  // Auto-derive cohort name from the default programme-offering term code.
  // Only applies while the cohort name has not been manually edited OR still matches the auto pattern.
  useEffect(() => {
    if (!defaultProgrammeOfferingTermCode) return
    if (!cohortNameAutoRef.current) return
    if (!isAutoGeneratedTermCode(defaultProgrammeOfferingTermCode)) return
    const suggested = buildCohortNameFromTermCode(defaultProgrammeOfferingTermCode, lang)
    setCohortName((current) =>
      isAutoGeneratedCohortName(current) || current === '' ? suggested : current,
    )
  }, [defaultProgrammeOfferingTermCode, lang])

  const progressionOptions = useMemo(
    (): readonly ProgrammeProgressionType[] => ['year_group', 'stage'],
    [],
  )

  const wizardSteps = useMemo(
    () =>
      [
        { title: t('faculties.wizard.steps.faculty') },
        { title: t('faculties.wizard.steps.programme') },
        { title: t('faculties.wizard.steps.cohort') },
        { title: t('faculties.wizard.steps.classGroup') },
        { title: t('faculties.wizard.steps.summary') },
      ] as const,
    [t],
  )

  useEffect(() => {
    const facultyIdParam = searchParams.get('facultyId')
    const institutionId = getUserInstitutionId()
    if (!facultyIdParam || !institutionId) {
      return
    }

    let cancelled = false

    void (async () => {
      try {
        const faculties = await listFacultiesByInstitution(institutionId)
        const match = faculties.find((f) => f.id === facultyIdParam)
        if (cancelled) {
          return
        }
        if (!match) {
          toast.error(t('faculties.wizard.prefill.facultyNotFound'))
          navigate('/institution_admin/faculties')
          return
        }
        setExistingFacultyId(match.id)
        setFacultyName(match.name ?? '')
        setFacultyDescription(match.description ?? '')
        setWizardStep(2)
      } catch {
        if (!cancelled) {
          toast.error(t('faculties.wizard.prefill.loadFailed'))
        }
      }
    })()

    return () => {
      cancelled = true
    }
  }, [searchParams, getUserInstitutionId, navigate, t])

  const handleBackToFaculties = () => {
    navigate('/institution_admin/faculties')
  }

  function handleWizardPrevious() {
    if (existingFacultyId && wizardStep === 2) {
      navigate(`/institution_admin/faculties/${existingFacultyId}/programmes`)
      return
    }
    setWizardStep((prev) => Math.max(1, prev - 1))
  }

  function handleWizardNext() {
    setWizardStep((prev) => Math.min(WIZARD_STEP_COUNT, prev + 1))
  }

  async function handleFinish() {
    const institutionId = getUserInstitutionId()

    if (!institutionId) {
      toast.error(t('faculties.wizard.submit.missingInstitution'))
      return
    }

    const sharedPayload = {
      programme: {
        name: programmeName,
        description: programmeDescription.trim() || null,
        durationYears,
        progressionType,
      },
      programmeOfferings: [
        {
          academicYear: defaultProgrammeOfferingYear,
          termCode: defaultProgrammeOfferingTermCode.trim() || null,
          status: 'draft' as const,
          dateRange: undefined,
        },
      ],
      cohort: {
        name: cohortName,
        description: null,
        academicYear: cohortAcademicYear,
      },
      cohortOfferings: [{ status: 'draft' as const, dateRange: undefined }],
      classGroup: {
        name: classGroupName,
        description: classGroupDescription.trim() || null,
      },
      classGroupOfferings: [{ status: 'draft' as const, dateRange: undefined }],
    }

    setIsSubmitting(true)
    try {
      if (existingFacultyId) {
        await appendProgrammeStructureToExistingFaculty({
          institutionId,
          facultyId: existingFacultyId,
          ...sharedPayload,
        })
        toast.success(t('faculties.wizard.submit.successAppendTitle'), {
          description: t('faculties.wizard.submit.successAppendDescription', {
            facultyName: facultyName.trim() || t('faculties.card.untitled'),
          }),
        })
        navigate(`/institution_admin/faculties/${existingFacultyId}/programmes`)
      } else {
        await createFacultyStructure({
          institutionId,
          faculty: {
            name: facultyName,
            description: facultyDescription.trim() || null,
          },
          ...sharedPayload,
        })
        toast.success(t('faculties.wizard.submit.successTitle'), {
          description: t('faculties.wizard.submit.successDescription', {
            facultyName: facultyName.trim() || t('faculties.card.untitled'),
          }),
        })
        navigate('/institution_admin/faculties')
      }
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : t('faculties.wizard.submit.errorFallback'),
      )
    } finally {
      setIsSubmitting(false)
    }
  }

  const breadcrumbValues = useMemo(
    () => [
      facultyName.trim(),
      programmeName.trim(),
      cohortName.trim(),
      classGroupName.trim(),
      t('faculties.wizard.steps.summary'),
    ],
    [facultyName, programmeName, cohortName, classGroupName, t],
  )

  const renderWizardStep = (_step: { title: string }, index: number) => {
    const priorItems = breadcrumbValues.slice(0, index).filter(Boolean)

    let stepContent: ReactNode

    switch (index) {
      case 0:
        stepContent = (
          <FacultyStep
            name={facultyName}
            onNameChange={setFacultyName}
            description={facultyDescription}
            onDescriptionChange={setFacultyDescription}
            readOnly={Boolean(existingFacultyId)}
          />
        )
        break

      case 1:
        stepContent = (
          <ProgrammeStep
            name={programmeName}
            onNameChange={setProgrammeName}
            description={programmeDescription}
            onDescriptionChange={setProgrammeDescription}
            durationYears={durationYears}
            onDurationChange={setDurationYears}
            progressionType={progressionType}
            onProgressionTypeChange={setProgressionType}
            progressionOptions={progressionOptions}
          />
        )
        break

      case 2:
        stepContent = (
          <CohortStep
            name={cohortName}
            onNameChange={(value) => {
              cohortNameAutoRef.current = false
              setCohortName(value)
            }}
            academicYear={cohortAcademicYear}
            onAcademicYearChange={setCohortAcademicYear}
          />
        )
        break

      case 3:
        stepContent = (
          <ClassGroupStep
            name={classGroupName}
            onNameChange={setClassGroupName}
            description={classGroupDescription}
            onDescriptionChange={setClassGroupDescription}
            termCode={defaultProgrammeOfferingTermCode}
          />
        )
        break

      case 4:
        stepContent = (
          <FacultyStructureSummaryStep
            intro={t('faculties.wizard.summary.intro')}
            rows={[
              { label: t('faculties.wizard.summary.rows.faculty'), value: facultyName || '—' },
              { label: t('faculties.wizard.summary.rows.programme'), value: programmeName || '—' },
              {
                label: t('faculties.wizard.summary.rows.programmeDuration'),
                value: t('faculties.wizard.programme.durationValue', { count: durationYears }),
              },
              {
                label: t('faculties.wizard.summary.rows.progression'),
                value: t(`faculties.wizard.programme.progression.${progressionType}`),
              },
              { label: t('faculties.wizard.summary.rows.cohort'), value: cohortName || '—' },
              {
                label: t('faculties.wizard.summary.rows.cohortAcademicYear'),
                value: String(cohortAcademicYear),
              },
              {
                label: t('faculties.wizard.summary.rows.classGroup'),
                value: classGroupName || '—',
              },
            ]}
            columns={{
              index: t('faculties.wizard.summary.columns.index'),
              label: t('faculties.wizard.summary.columns.label'),
              status: t('faculties.wizard.summary.columns.status'),
              startsAt: t('faculties.wizard.summary.columns.startsAt'),
              endsAt: t('faculties.wizard.summary.columns.endsAt'),
            }}
            sectionTitles={{
              programmeOfferings: t('faculties.wizard.summary.sections.programmeOfferings'),
              cohortOfferings: t('faculties.wizard.summary.sections.cohortOfferings'),
              classGroupOfferings: t('faculties.wizard.summary.sections.classGroupOfferings'),
            }}
            programmeOfferings={[]}
            cohortOfferings={[]}
            classGroupOfferings={[]}
          />
        )
        break

      default:
        return null
    }

    return (
      <div className="flex w-full flex-col gap-4">
        <WizardBreadcrumb items={priorItems} />
        {stepContent}
      </div>
    )
  }

  return (
    <InstitutionAdminWorkspaceShell>
      <div className="mx-auto flex w-full max-w-4xl flex-col gap-8 px-2 pb-12 pt-4 animate-in fade-in-0 slide-in-from-bottom-4 motion-safe:duration-300">
        <div className="flex flex-col gap-4 animate-in fade-in-0 slide-in-from-bottom-3 motion-safe:duration-300">
          <Button
            variant="ghost"
            type="button"
            className="w-fit gap-2 px-0"
            onClick={handleBackToFaculties}
          >
            <ArrowLeft className="size-4" />
            {t('faculties.wizard.backToList')}
          </Button>
          <div>
            <Text
              as="h1"
              variant="h1"
              className="text-2xl font-bold"
            >
              {t('faculties.wizard.pageTitle')}
            </Text>
            <Text
              as="p"
              variant="body"
              color="muted"
            >
              {t('faculties.createSubtitle')}
            </Text>
          </div>
        </div>

        <div className="flex w-full flex-col gap-6 animate-in fade-in-0 slide-in-from-bottom-2 motion-safe:duration-300">
          <StepperProgressBarTitles
            steps={wizardSteps}
            value={wizardStep}
            defaultValue={1}
            onValueChange={setWizardStep}
            className="mx-auto max-w-4xl space-y-8"
            renderContent={renderWizardStep}
          />

          <div className="mx-auto flex w-full max-w-4xl flex-wrap justify-between gap-3 border-t border-border pt-6 animate-in fade-in-0 slide-in-from-bottom-2 motion-safe:duration-300">
            <Button
              type="button"
              variant="outline"
              onClick={handleWizardPrevious}
              disabled={wizardStep <= 1}
            >
              {t('faculties.wizard.actions.previous')}
            </Button>

            {wizardStep < WIZARD_STEP_COUNT ? (
              <Button
                type="button"
                variant="darkblue"
                onClick={handleWizardNext}
              >
                {t('faculties.wizard.actions.next')}
              </Button>
            ) : (
              <Button
                type="button"
                variant="darkblue"
                onClick={handleFinish}
                disabled={isSubmitting}
              >
                {isSubmitting
                  ? t('faculties.wizard.actions.finishing')
                  : t('faculties.wizard.actions.finish')}
              </Button>
            )}
          </div>
        </div>
      </div>
    </InstitutionAdminWorkspaceShell>
  )
}
