-- ===================================================================
-- INSERT STATEMENT: Kreiskliniken Reutlingen gGmbH
-- ===================================================================
-- Data gathered from: 
-- - https://www.kreiskliniken-reutlingen.de/impressum/
-- - https://www.linkedin.com/company/kreiskliniken-rt
-- - Official website and Wikipedia
-- ===================================================================

INSERT INTO public.institutions (
  -- Basic Information
  name,
  slug,
  type,
  status,
  description,
  
  -- Legal Information (from Impressum)
  legal_name,
  legal_form,
  registration_number,
  tax_id,
  vat_id,
  
  -- Contact Information
  email,
  phone,
  website,
  
  -- Primary Contact (Geschäftsführer)
  primary_contact_name,
  primary_contact_role,
  primary_contact_email,
  primary_contact_phone,
  
  -- Billing Information
  billing_email,
  billing_contact_name,
  billing_contact_phone,
  invoice_language,
  payment_terms,
  
  -- Address (JSONB format)
  address,
  
  -- Hospital-Specific Information
  institution_number,
  number_of_beds,
  departments,
  accreditation,
  
  -- Social Links (JSONB format)
  social_links,
  
  -- Metadata
  image_url,
  
  -- Timestamps (auto-generated)
  created_at,
  updated_at
)
VALUES (
  -- Basic Information
  'Kreiskliniken Reutlingen',
  'kreiskliniken-reutlingen',
  'hospital',
  'active',
  'Die Kreiskliniken Reutlingen gGmbH betreiben das Klinikum am Steinenberg in Reutlingen und die Albklinik in Münsingen. Mit rund 850 Betten, über 2.600 Beschäftigten und jährlich über 95.000 Patienten zählen wir zu den bedeutendsten Gesundheitseinrichtungen der Region und sind der größte kommunale Arbeitgeber.',
  
  -- Legal Information
  'Kreiskliniken Reutlingen gGmbH',
  'ggmbh',
  'HRB 354274',
  '78042/81195',
  'DE229860840',
  
  -- Contact Information
  'info@klin-rt.de',
  '+49 7121 200-0',
  'https://www.kreiskliniken-reutlingen.de',
  
  -- Primary Contact (Geschäftsführer)
  'Dominik Nusser',
  'Geschäftsführer',
  'info@klin-rt.de',
  '+49 7121 200-0',
  
  -- Billing Information
  'info@klin-rt.de',
  'Verwaltung',
  '+49 7121 200-4434',
  'de',
  30,
  
  -- Address (JSONB format) - Steinenbergstr. 31, 72764 Reutlingen
  jsonb_build_object(
    'street', 'Steinenbergstraße 31',
    'addressLine2', NULL,
    'postalCode', '72764',
    'city', 'Reutlingen',
    'state', 'Baden-Württemberg',
    'country', 'Germany'
  ),
  
  -- Hospital-Specific Information
  NULL, -- institution_number (IK-Nummer not found in public sources)
  850, -- number_of_beds (ca. 850 Betten total across locations)
  ARRAY[
    'Allgemein-, Viszeral- und Thoraxchirurgie',
    'Anästhesiologie, operative Intensivmedizin, Notfallmedizin, Schmerztherapie und Palliativmedizin',
    'Frauenklinik',
    'Gefäßchirurgie',
    'Kinder- und Jugendmedizin',
    'Medizinische Klinik I',
    'Medizinische Klinik II (Kardiologie, Angiologie, Intensivmedizin)',
    'Neurochirurgie und Wirbelsäulenchirurgie',
    'Neurologie und Frührehabilitation',
    'Unfallchirurgie, Orthopädie und Sportmedizin',
    'Urologische Klinik',
    'Interdisziplinäre Notfallmedizin',
    'Altersmedizin',
    'Innere Medizin Münsingen',
    'Schmerzklinik',
    'Allgemeinchirurgie Münsingen'
  ],
  'Akademisches Lehrkrankenhaus der Universität Tübingen',
  
  -- Social Links (JSONB format)
  jsonb_build_object(
    'linkedin', 'https://www.linkedin.com/company/kreiskliniken-rt',
    'instagram', 'https://www.instagram.com/kreiskliniken.rt'
  ),
  
  -- Metadata
  'https://www.kreiskliniken-reutlingen.de/fileadmin/_processed_/6/2/csm_KKR_Logo_RGB_300dpi_fa5e5e5e5e.png',
  
  -- Timestamps (auto-generated by DEFAULT NOW())
  NOW(),
  NOW()
);
