export { TeacherClassroomsEmpty } from './components/TeacherClassroomsEmpty'
export { TeacherCoursesEmpty } from './components/TeacherCoursesEmpty'
export { TeacherView } from './components/TeacherView'
export { Dashboard as TeacherDashboard } from './pages/dashboard'
export { TeacherCoursesPage } from './pages/courses'
export { TeacherSchedulePage } from './pages/schedule'
export { TeacherCloudPage } from './pages/cloud'
export { TeacherNotesPage } from './pages/notes'
export { TeacherTasksPage } from './pages/tasks'
export { TeacherSettingsPage } from './pages/settings'
export { GameStudio } from './pages/game-studio'
export { Chat as TeacherChat } from './pages/chat'
export { TeacherViewPage } from './pages/view'
