export { TeacherClassroomsEmpty } from './components/TeacherClassroomsEmpty'
export { TeacherCoursesEmpty } from './components/TeacherCoursesEmpty'
export { TeacherView } from './components/TeacherView'
export { Dashboard as TeacherDashboard } from './pages/dashboard'
export { TeacherFilesPage } from './pages/files'
export { TeacherNotesPage } from './pages/notes'
export { TeacherTasksPage } from './pages/tasks'
export { TeacherSettingsPage } from './pages/settings'
export { GameStudio } from './pages/game-studio'
export { Chat as TeacherChat } from './pages/chat'
export { TeacherViewPage } from './pages/view'
